# Generated by Django 2.2.16 on 2022-05-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220514_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=0, null=True, verbose_name='Время приготовления'),
        ),
    ]
