# Generated by Django 2.2.16 on 2022-05-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220516_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
